name: Coverage

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup nightly toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov --features github-ci,moveable-feasts --workspace --lcov --output-path lcov.info
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          path: lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@v2.3.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
